In [6]:
import numpy as np
from numpy import random

arr = random.randint(0, 100, size=(3, 3))
print("Numpy Matrix:\n", arr)

Numpy Matrix:
 [[24 49 98]
 [57 46 55]
 [24 95 85]]


In [4]:
#Calculate the determinant
det = np.linalg.det(arr)
print("Determinant of 3x3 matrix:", int(det))

Determinant of 3x3 matrix: -67668


In [8]:
#Find the inverse of the matrix
inv = np.linalg.inv(arr)
print("Inverse of 3x3 matrix:\n", inv)

Inverse of 3x3 matrix:
 [[-0.00602677  0.02358004 -0.00830916]
 [-0.01615542 -0.00142993  0.0195515 ]
 [ 0.01975774 -0.00505974 -0.00774085]]
